# Generated by Django 2.2.4 on 2020-04-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appmodel",
            name="api_key",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
